# Generated by Django 5.2.7 on 2025-11-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMSwebsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='profile_submitted',
            field=models.BooleanField(default=False, help_text='Indicates if the employee has submitted their profile information', verbose_name='Profile Submitted'),
        ),
    ]
