# Generated by Django 5.2.7 on 2025-11-22 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMSwebsite', '0002_employees_profile_submitted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('hr', 'HR Manager'), ('finance', 'Finance Manager'), ('employee', 'Employee'), ('manager', 'Department Manager')], default='employee', max_length=20),
        ),
        migrations.CreateModel(
            name='SalaryDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disbursement_id', models.CharField(help_text='Unique transaction ID from bank API', max_length=100, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_employees', models.IntegerField(default=0)),
                ('successful_payments', models.IntegerField(default=0)),
                ('failed_payments', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('partial', 'Partially Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_method', models.CharField(choices=[('bank_api', 'Bank API'), ('manual', 'Manual Transfer'), ('other', 'Other')], default='bank_api', max_length=20)),
                ('bank_api_response', models.JSONField(blank=True, help_text='Response from bank API', null=True)),
                ('bank_api_request', models.JSONField(blank=True, help_text='Request sent to bank API', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursements_initiated', to=settings.AUTH_USER_MODEL)),
                ('payroll', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='EMSwebsite.payroll')),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='SalaryDisbursementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bank_account_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction ID from bank', max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('bank_response', models.JSONField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('disbursement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='EMSwebsite.salarydisbursement')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EMSwebsite.employees')),
                ('payroll_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursement_records', to='EMSwebsite.payrollrecord')),
            ],
            options={
                'ordering': ['-processed_at'],
                'unique_together': {('disbursement', 'payroll_record')},
            },
        ),
    ]
