# Generated by Django 5.2.7 on 2025-11-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EISwebsite', '0003_alter_userprofile_role_salarydisbursement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='temp_password',
            field=models.CharField(blank=True, editable=False, help_text='Temporary storage for generated password - cleared after display', max_length=128, null=True),
        ),
    ]
