# Generated by Django 5.2.7 on 2025-11-27 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EISwebsite', '0004_add_temp_password_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='backup_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Backup and restore configuration'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='notification_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Email, push, and in-app notification preferences'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='privacy_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Privacy preferences and data sharing settings'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='security_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Security preferences including 2FA, session management'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('employee', 'Employee Report'), ('payroll', 'Payroll Report'), ('attendance', 'Attendance Report'), ('department', 'Department Report'), ('leave', 'Leave Report'), ('loan', 'Loan Report')], max_length=50),
        ),
        migrations.AlterField(
            model_name='reporttemplate',
            name='report_type',
            field=models.CharField(choices=[('employee', 'Employee Report'), ('payroll', 'Payroll Report'), ('attendance', 'Attendance Report'), ('department', 'Department Report'), ('leave', 'Leave Report'), ('loan', 'Loan Report')], max_length=50),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='font_size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=8),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='sidebar_width',
            field=models.CharField(choices=[('compact', 'Compact'), ('normal', 'Normal'), ('wide', 'Wide')], default='normal', max_length=8),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='theme',
            field=models.CharField(choices=[('default', 'Default'), ('indigo', 'Indigo'), ('emerald', 'Emerald'), ('crimson', 'Crimson')], default='default', max_length=32),
        ),
    ]
