# Generated by Django 5.2.7 on 2025-11-27 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EISwebsite', '0005_add_settings_json_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salaryincrement',
            options={'ordering': ['-effective_date', '-applied_at']},
        ),
        migrations.AddField(
            model_name='employees',
            name='increment_cycle_months',
            field=models.IntegerField(default=6, help_text='Number of months between increments'),
        ),
        migrations.AddField(
            model_name='employees',
            name='last_increment_date',
            field=models.DateField(blank=True, help_text='Date of last salary increment', null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='next_increment_date',
            field=models.DateField(blank=True, help_text='Calculated next increment date (6 months from last increment or joining date)', null=True),
        ),
        migrations.AddField(
            model_name='salaryincrement',
            name='increase_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Absolute increase amount', max_digits=12),
        ),
        migrations.AddField(
            model_name='salaryincrement',
            name='is_automatic',
            field=models.BooleanField(default=False, help_text='True if increment was applied automatically by system'),
        ),
        migrations.AddField(
            model_name='salaryincrement',
            name='notification_sent',
            field=models.BooleanField(default=False, help_text='True if notifications were sent for this increment'),
        ),
        migrations.CreateModel(
            name='IncrementSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('increment_percentage', models.DecimalField(decimal_places=2, default=5.0, help_text='Default percentage increase for 6-month increments', max_digits=6)),
                ('increment_amount', models.DecimalField(decimal_places=2, default=0, help_text='Fixed increment amount (if set, overrides percentage). Set to 0 to use percentage.', max_digits=12)),
                ('use_percentage', models.BooleanField(default=True, help_text='If True, use percentage. If False, use fixed amount.')),
                ('cycle_months', models.IntegerField(default=6, help_text='Number of months between increments')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable automatic increments')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_increment_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Increment Setting',
                'verbose_name_plural': 'Increment Settings',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('increment', 'Salary Increment'), ('birthday', 'Birthday'), ('payroll', 'Payroll'), ('leave', 'Leave Request'), ('system', 'System Notification')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_object_id', models.IntegerField(blank=True, help_text='ID of related object (e.g., increment ID)', null=True)),
                ('related_object_type', models.CharField(blank=True, help_text='Type of related object', max_length=50, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='EISwebsite__recipie_8ad300_idx'), models.Index(fields=['notification_type', 'created_at'], name='EISwebsite__notific_f41a5b_idx')],
            },
        ),
    ]
