# Generated by Django 4.2.24 on 2025-12-05 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EISwebsite', '0006_add_automatic_increment_system'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AlterField(
            model_name='attendancesettings',
            name='work_end_time',
            field=models.TimeField(default='18:00'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('increment', 'Salary Increment'), ('birthday', 'Birthday'), ('payroll', 'Payroll'), ('leave', 'Leave Request'), ('attendance', 'Attendance'), ('system', 'System Notification')], max_length=20),
        ),
    ]
