# Generated by Django 4.2.24 on 2025-12-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMSwebsite', '0007_delete_employee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('early-in', 'Early-in'), ('early-out', 'Early-out'), ('leave', 'On Leave'), ('overtime', 'Overtime'), ('late-sitting', 'Late Sitting'), ('weekend', 'Weekend Work')], default='present', max_length=20),
        ),
    ]
