# Generated by Django 4.2.24 on 2025-12-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EISwebsite', '0008_employee_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='team',
            field=models.CharField(blank=True, choices=[('', '-- Select Team --'), ('Sir Ahsan', 'Sir Ahsan'), ('Sir Faisal', 'Sir Faisal'), ('Sir Zubair', 'Sir Zubair'), ('Sir Govinda', 'Sir Govinda'), ('Sir Suhail', 'Sir Suhail'), ('HR', 'HR'), ('Social media', 'Social media'), ('Ecommerce', 'Ecommerce'), ('Accounts', 'Accounts'), ('Admin', 'Admin'), ('Sir Faizan', 'Sir Faizan'), ('Sir Ahtisham', 'Sir Ahtisham')], max_length=50, null=True, verbose_name='Team'),
        ),
    ]
