# Generated by Django 5.2.7 on 2025-12-08 14:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMSwebsite', '0008_employee_alter_attendance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAdditionalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='employee_documents/additional/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_documents', to='EMSwebsite.employees')),
            ],
            options={
                'verbose_name': 'Additional Document',
                'verbose_name_plural': 'Additional Documents',
            },
        ),
    ]
