# Generated by Django 5.2.7 on 2025-12-08 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMSwebsite', '0009_alter_employees_team'),
        ('EMSwebsite', '0009_employeeadditionaldocument'),
    ]

    operations = [
    ]
