# Generated by Django 4.2.7 on 2025-12-29 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EISwebsite', '0011_salarysliprequest_policy_complaint_aichatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('early-in', 'Early-in'), ('early-out', 'Early-out'), ('leave', 'On Leave'), ('overtime', 'Overtime'), ('late-sitting', 'Late Sitting'), ('weekend', 'Weekend Work'), ('holiday', 'Holiday')], default='present', max_length=20),
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Holiday Name')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(help_text='For single day holidays, use the same date as start date', verbose_name='End Date')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to deactivate this holiday', verbose_name='Active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_holidays', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Holiday',
                'verbose_name_plural': 'Holidays',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='EISwebsite__start_d_c29da0_idx'), models.Index(fields=['is_active'], name='EISwebsite__is_acti_2e718e_idx')],
            },
        ),
    ]
