# Generated by Django 5.2.7 on 2026-01-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMSwebsite', '0012_alter_attendance_status_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('sick', 'Sick Leave'), ('vacation', 'Vacation'), ('personal', 'Personal Leave'), ('annual', 'Annual Leave'), ('business', 'Business Leave'), ('other', 'Other Leave'), ('', 'No Leave')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('early-in', 'Early-in'), ('early-out', 'Early-out'), ('leave', 'On Leave'), ('overtime', 'Overtime'), ('late-sitting', 'Late Sitting'), ('weekend', 'Weekend Work')], default='present', max_length=20),
        ),
        migrations.DeleteModel(
            name='Holiday',
        ),
    ]
