# Generated by Django 4.2.7 on 2026-01-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EISwebsite', '0014_add_holiday_date_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='grace_period_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Grace period in minutes for late arrival (e.g., 15). Leave empty to use global settings.', null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='office_end_time',
            field=models.TimeField(blank=True, help_text='Department check-out time (e.g., 18:00). Leave empty to use global settings.', null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='office_start_time',
            field=models.TimeField(blank=True, help_text='Department check-in time (e.g., 09:00). Leave empty to use global settings.', null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='use_custom_timings',
            field=models.BooleanField(default=False, help_text='Enable custom office timings for this department. If disabled, uses global attendance settings.'),
        ),
    ]
