# Generated by Django 4.2.7 on 2026-01-17 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EMSwebsite', '0015_department_grace_period_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZKDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Device name/identifier', max_length=100, unique=True)),
                ('ip_address', models.CharField(help_text='Device IP address', max_length=50)),
                ('port', models.IntegerField(default=4370, help_text='Device port (default: 4370)')),
                ('timeout', models.IntegerField(default=5, help_text='Connection timeout in seconds')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('device_name', models.CharField(blank=True, max_length=100, null=True)),
                ('firmware_version', models.CharField(blank=True, max_length=50, null=True)),
                ('device_model', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('connecting', 'Connecting'), ('error', 'Error')], default='offline', max_length=20)),
                ('last_connected', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable device monitoring')),
                ('auto_sync', models.BooleanField(default=True, help_text='Automatically sync attendance')),
                ('realtime_enabled', models.BooleanField(default=True, help_text='Enable real-time event monitoring')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ZK Device',
                'verbose_name_plural': 'ZK Devices',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_type', models.CharField(choices=[('fingerprint', 'Fingerprint'), ('face', 'Face Recognition')], max_length=20)),
                ('template_index', models.IntegerField(blank=True, help_text='Template index on device', null=True)),
                ('template_data', models.BinaryField(blank=True, help_text='Template data (if stored)', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_logs', to='EMSwebsite.zkdevice')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_logs', to='EMSwebsite.employees')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enrollment Log',
                'verbose_name_plural': 'Enrollment Logs',
                'ordering': ['-started_at'],
                'unique_together': {('device', 'employee', 'enrollment_type', 'template_index')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(help_text='User ID from device', max_length=50)),
                ('user_name', models.CharField(blank=True, help_text='User name from device', max_length=200, null=True)),
                ('event_type', models.CharField(choices=[('check_in', 'Check In'), ('check_out', 'Check Out'), ('fingerprint', 'Fingerprint Verification'), ('face', 'Face Verification'), ('rfid', 'RFID Card'), ('password', 'Password'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('timestamp', models.DateTimeField(help_text='Event timestamp from device')),
                ('verification_mode', models.IntegerField(default=0, help_text='Verification mode (0=password, 1=fingerprint, 15=face, etc.)')),
                ('raw_data', models.JSONField(blank=True, help_text='Raw event data from device', null=True)),
                ('is_processed', models.BooleanField(default=False, help_text='Whether this log has been processed into Attendance record')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attendance_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_logs', to='EMSwebsite.attendance')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='EMSwebsite.zkdevice')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='device_attendance_logs', to='EMSwebsite.employees')),
            ],
            options={
                'verbose_name': 'Attendance Log',
                'verbose_name_plural': 'Attendance Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='EMSwebsite__timesta_bc4ded_idx'), models.Index(fields=['device', '-timestamp'], name='EMSwebsite__device__a1895c_idx'), models.Index(fields=['employee', '-timestamp'], name='EMSwebsite__employe_b21d65_idx'), models.Index(fields=['is_processed'], name='EMSwebsite__is_proc_d8cffc_idx')],
            },
        ),
    ]
