# Generated by Django 5.2.7 on 2026-01-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMSwebsite', '0016_zkdevice_enrollmentlog_attendancelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='zkdevice',
            name='password',
            field=models.CharField(blank=True, help_text='Device admin password (if required). Leave empty if no password.', max_length=50, null=True),
        ),
    ]
