# Generated by Django 4.2.7 on 2026-05-12 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EMSwebsite', '0017_zkdevice_password'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendancelog',
            new_name='EMSwebsite__timesta_6b03b8_idx',
            old_name='EMSwebsite__timesta_bc4ded_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancelog',
            new_name='EMSwebsite__device__fadc51_idx',
            old_name='EMSwebsite__device__a1895c_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancelog',
            new_name='EMSwebsite__employe_bbea45_idx',
            old_name='EMSwebsite__employe_b21d65_idx',
        ),
        migrations.RenameIndex(
            model_name='attendancelog',
            new_name='EMSwebsite__is_proc_54a024_idx',
            old_name='EMSwebsite__is_proc_d8cffc_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='EMSwebsite__recipie_a76108_idx',
            old_name='EMSwebsite__recipie_8ad300_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='EMSwebsite__notific_35e165_idx',
            old_name='EMSwebsite__notific_f41a5b_idx',
        ),
    ]
