# Generated by Django 6.0.5 on 2026-05-19 04:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EMSwebsite', '0018_rename_emswebsite__timesta_bc4ded_idx_emswebsite__timesta_6b03b8_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='max_task_workload',
            field=models.PositiveIntegerField(default=3, help_text='Maximum number of tasks this employee can be assigned simultaneously'),
        ),
        migrations.AddField(
            model_name='employees',
            name='skills',
            field=models.JSONField(blank=True, default=list, help_text="List of skills e.g. ['Python', 'SQL', 'ML']"),
        ),
        migrations.CreateModel(
            name='AssignmentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('required_skills', models.JSONField(default=list, help_text="List of required skills e.g. ['Python', 'SQL']")),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'Medium'), (4, 'High'), (5, 'Critical')], default=2)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='EMSwebsite.employees')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assignment Task',
                'verbose_name_plural': 'Assignment Tasks',
                'ordering': ['-priority', 'created_at'],
            },
        ),
    ]
